# Base configs
baseurl: "https://ramyaartist.github.io/Arts/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
# google_analytics: "UA-46465113-2"

# UI configs
title: "Arts by Ramya Raman"
subtitle: "See the world through my eyes!"
author: "Ramya Raman"
header:
 title: "Arts"
 subtitle: "by Ramya Raman"
footer:
 name: "Hey there, my name is Ramya"
 bio: "I am a Chemist from Vellore who loves nature and art. In my free time, I love to capture nature in a paper"
web_design: "Tim"
social_urls:
# #   facebook: "https://www.facebook.com/ramswaroop"
# #   twitter: "https://www.twitter.com/ram__patra"
# #   instagram: "https://www.instagram.com/RamyaRaman"
  linkedin: "https://www.linkedin.com/in/ramya-raman-994989198/"
  github: "https://github.com/RamyaArtist"
